/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package art_gallery;

import dao.EmployeeDao;
import dao.CategoryDao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Employee;
import model.Category;

/**
 *
 * @author Admin
 */
public class ViewEditDeleteEmployee extends javax.swing.JFrame {

    /**
     * Creates new form ViewEditDeleteEmployee
     */
    public ViewEditDeleteEmployee() {
        initComponents();
        jButton_save2.setEnabled(false);
        jButton_delete.setEnabled(false);
    }

    public void validateField() {
        String employee_name = jTextField_name.getText();
        String nid = jTextField_nid.getText();
        String salary = (String) jComboBox_salary.getSelectedItem();
        if (!employee_name.equals("") && !nid.equals("") && salary != null) {
            jButton_save2.setEnabled(true);
        } else {
            jButton_save2.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        j_id = new javax.swing.JLabel();
        j_name = new javax.swing.JLabel();
        j_nid2 = new javax.swing.JLabel();
        j_salary2 = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jTextField_nid = new javax.swing.JTextField();
        jComboBox_salary = new javax.swing.JComboBox<>();
        jLabel_idans = new javax.swing.JLabel();
        jButton_delete = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jButton_save2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View,Edit,Delete Of Employee");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 358, 46));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1035, 0, 35, 38));

        j_id.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        j_id.setForeground(new java.awt.Color(255, 255, 255));
        j_id.setText("ID:");
        getContentPane().add(j_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 135, -1, -1));

        j_name.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        j_name.setForeground(new java.awt.Color(255, 255, 255));
        j_name.setText("Employee Name:");
        getContentPane().add(j_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        j_nid2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        j_nid2.setForeground(new java.awt.Color(255, 255, 255));
        j_nid2.setText("Nid:");
        getContentPane().add(j_nid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 236, -1, -1));

        j_salary2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        j_salary2.setForeground(new java.awt.Color(255, 255, 255));
        j_salary2.setText("Salary:");
        getContentPane().add(j_salary2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 283, -1, -1));

        jTextField_name.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_nameKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 183, 383, -1));

        jTextField_nid.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField_nid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_nidKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 233, 383, -1));

        jComboBox_salary.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        getContentPane().add(jComboBox_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 280, 383, -1));

        jLabel_idans.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_idans.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_idans.setText("00");
        getContentPane().add(jLabel_idans, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        jButton_delete.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButton_delete.setText("Sack");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        jButton_clear.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        jButton_clear.setText("Clear");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 361, -1, -1));

        jButton_save2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton_save2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton_save2.setText("Update");
        jButton_save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_save2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_save2, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 361, -1, -1));

        jTable1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Nid", "Salary"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 88, 432, 410));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-840, -650, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nameKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_jTextField_nameKeyReleased

    private void jTextField_nidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nidKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_jTextField_nidKeyReleased

    private void jButton_save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_save2ActionPerformed
        // TODO add your handling code here:
        Employee employee = new Employee();
        int id = Integer.parseInt(jLabel_idans.getText());
        employee.setId(id);
        employee.setEmployee_name(jTextField_name.getText());
        employee.setSalary((String) jComboBox_salary.getSelectedItem());
        employee.setNid(jTextField_nid.getText());
        EmployeeDao.update(employee);
        setVisible(false);
        new ViewEditDeleteEmployee().setVisible(true);
    }//GEN-LAST:event_jButton_save2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<Employee> list = EmployeeDao.getAllRecords();
        Iterator<Employee> itr = list.iterator();
        while (itr.hasNext()) {
            Employee employeeObj = itr.next();
            dtm.addRow(new Object[]{employeeObj.getId(), employeeObj.getEmployee_name(), employeeObj.getSalary(), employeeObj.getNid()});

        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String id = model.getValueAt(index, 0).toString();
        jLabel_idans.setText(id);
        String employee_name = model.getValueAt(index, 1).toString();
        jTextField_name.setText(employee_name);
        String salary = model.getValueAt(index, 2).toString();
        String nid = model.getValueAt(index, 3).toString();
        jTextField_nid.setText(nid);

        jButton_save2.setEnabled(true);
        jButton_delete.setEnabled(true);

        jComboBox_salary.removeAllItems();
        jComboBox_salary.addItem(salary);
        ArrayList<Category> categoryList = CategoryDao.getAllRecords();
        Iterator<Category> categoryItr = categoryList.iterator();
        while (categoryItr.hasNext()) {
            Category categoryObj = categoryItr.next();
            if (!categoryObj.getName().equals(salary)) {
                jComboBox_salary.addItem(categoryObj.getName());
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // TODO add your handling code here:
        String id = jLabel_idans.getText();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to sack the employee", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            EmployeeDao.delete(id);
            setVisible(false);
            new ViewEditDeleteEmployee().setVisible(true);
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ViewEditDeleteEmployee().setVisible(true);
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEditDeleteEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_save2;
    private javax.swing.JComboBox<String> jComboBox_salary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_idans;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_nid;
    private javax.swing.JLabel j_id;
    private javax.swing.JLabel j_name;
    private javax.swing.JLabel j_nid2;
    private javax.swing.JLabel j_salary2;
    // End of variables declaration//GEN-END:variables
}
